### PR TITLE
Perf improvements for `all_equal_simd`

### PR DESCRIPTION
**Pull request by smu160**
This is a draft PR to work on #10.

### CODE REVIEW

**Comment by PaulDotSH** [comment]
Libraries should ignore cargo.lock, can you or @LaihoE add it to .gitignore and remove it?

**Comment by LaihoE** [comment]
> Libraries should ignore cargo.lock, can you or @LaihoE add it to .gitignore and remove it?

done.

**Comment by LaihoE** [comment]
Thanks, looks good!. Btw be careful with dropping the n in tests too low as it can cause the simd part to never be run.

**Comment by LaihoE** [comment]
I'm currently working on unrolling the position function. Could you add the UNROLL_FACTOR to the lib.rs next to the SIMD_LEN? I think we should have the same UNROLL_FACTOR for all function (at least for now).

**Comment by smu160** [comment]
> I'm currently working on unrolling the position function. Could you add the UNROLL_FACTOR to the lib.rs next to the SIMD_LEN? I think we should have the same UNROLL_FACTOR for all function (at least for now).

Do you want that here or as a hotfix in a separate PR?

**Comment by LaihoE** [comment]
> > I'm currently working on unrolling the position function. Could you add the UNROLL_FACTOR to the lib.rs next to the SIMD_LEN? I think we should have the same UNROLL_FACTOR for all function (at least for now).
> 
> Do you want that here or as a hotfix in a separate PR?

just add it to this pr :+1:

**Comment by LaihoE** [comment]
Looks good, can we merge this?

**Comment by smu160** [comment]
Hi @LaihoE,

Apologies for the belated reply. I'm going to get this PR ready for review now. I'll post the before/after benchmarks as well.

Thank you!!

**Comment by smu160** [comment]
This PR is a bit outdated given the new changes. I will create a new PR for running benchmarks and plotting the (criterion) data, first.

**Pull request closed without merging**
